name: lnmq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  uuid: ^4.5.1
  flutter_rating_bar: ^4.0.1
  http: ^1.2.1 # Hoặc phiên bản mới nhất
  url_launcher: ^6.2.5 # Hoặc phiên bản mới nhất
  google_maps_flutter: ^2.6.0  
  google_sign_in: ^6.2.1 # Đảm bảo đã có nếu bạn muốn dùng Google Sign-In
  geolocator: ^11.0.0 # Đảm bảo đã có nếu bạn muốn dùng vị trí

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro/BeVietnamPro-Bold.ttf
          weight: 700
